name: Build and Upload wheel

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build-wheel:
    name: Build wheel
    runs-on: ${{ matrix.platform[0] }}
    permissions:
      id-token: write

    strategy:
      matrix:
        platform:
          - [ubuntu-22.04, manylinux_x86_64]
        python: ["cp38", "cp39", "cp310", "cp311", "cp312"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build wheels
        uses: pypa/cibuildwheel@faf86a6ed7efa889faf6996aa23820831055001a  # v2.23.3
        env:
          CIBW_BUILD: ${{ matrix.python }}-${{ matrix.platform[1] }}

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.python }}-${{ matrix.platform[1] }}
          path: ./wheelhouse/*.whl

      - name: Publish release distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1.12
        with:
          verbose: true
          packages-dir: ./wheelhouse/